version: "3.7"

services:
  rust:
    image: rust:latest
    container_name: rust
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    environment:
      USER: root
      CARGO_BUILD_TARGET_DIR: /app/linux
